# a very minimal declarative config file
_format_version: "2.1"
_transform: false
services:
  - name: grpc-service
    url: http://grpc-service.service.dc1.consul
    routes:
      - name: grpc_route
        paths:
          - /gprc
